apiVersion: v1
kind: Service
metadata:
  name: {{ include "boardgame.fullname" .}}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boardgame.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "boardgame.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}